apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app
spec:
  type: NodePort # Use LoadBalancer if deploying to cloud
  ports:
    - port: 8001          # Service port
      targetPort: 8001    # Container port
      nodePort: 30007     # Node port (only for NodePort type)
  selector:
    app: test-app
